<a href="https://colab.research.google.com/github/Shah4l/deep-learning-projects/blob/main/1_RNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
import numpy as np
from tensorflow.keras.layers import Dense,SimpleRNN
from tensorflow.keras.models import Sequential

In [ ]:
x=np.array([[[1],[2],[3]],
            [[2],[3],[4]],
            [[20],[21],[22]],
            [[3],[4],[5]],
            [[4],[5],[6]]])
y=np.array([4,5,23,6,7])

In [ ]:
x

array([[[ 1],
        [ 2],
        [ 3]],

       [[ 2],
        [ 3],
        [ 4]],

       [[20],
        [21],
        [22]],

       [[ 3],
        [ 4],
        [ 5]],

       [[ 4],
        [ 5],
        [ 6]]])

In [ ]:
y

array([ 4,  5, 23,  6,  7])

In [ ]:
model=Sequential()
model.add(SimpleRNN(8,activation='relu',input_shape=(3,1)))
model.add(Dense(1))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [ ]:
model.compile(optimizer='adam',loss='mse')

In [ ]:
model.fit(x,y,epochs=300,verbose=1)

Epoch 1/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - loss: 272.7410
Epoch 2/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 268.8247
Epoch 3/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - loss: 264.9193
Epoch 4/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - loss: 261.0251
Epoch 5/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - loss: 257.1427
Epoch 6/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - loss: 253.2663
Epoch 7/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 249.3900
Epoch 8/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 245.5268
Epoch 9/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 241.6773
Epoch 10/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 237.8421
Epoch 11/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - loss: 234.0219
Epoch 12/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 230.2044
Epoch 13/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - loss: 226.3859
Epoch 14/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 222.5828
Epoch 15/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 

In [ ]:
inp=np.array([[[100],[101],[102]]])
y_pred=model.predict(inp)
y_pred

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 215ms/step


array([[109.05165]], dtype=float32)